apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: todo
  description: todo API
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - todo
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: ./docs/todo.oas.json
