apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: todo
  description: todo API
  tags:
    - todo
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition:
    $text: ./ocs/todo.oas.yaml